### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [NativeScript/docs-v7#1]
Hi,

Are there any ready-to-compile example apps?

-G

**Comment by ligaz** [comment]
Hi Geoffrey,

Currently we have a single example that illustrates the core concepts of NativeScript. You can check the sample [here](https://github.com/telerik/nativescript-sample-cuteness) but be aware that it only works in the context of [AppBuilder](http://www.telerik.com/appbuilder). 

My suggestion for you is to sign-up for our [NativeScript Insiders](http://www.telerik.com/nativescript-insiders-signup) so that you can explorer what we currently have and share your feedback.

-sdobrev
