### ISSUE TITLE
Add Angular bootstrap section for createFrameOnBootstrap

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#1206]
Add a documentation section explaining bootstrapping with `createFrameOnBootstrap: true `

Related to [https://github.com/NativeScript/nativescript-angular/issues/1384#issuecomment-397572618](https://github.com/NativeScript/nativescript-angular/issues/1384#issuecomment-397572618)

**Comment by NickIliev** [comment]
Resolved via [https://github.com/NativeScript/docs/pull/1243](https://github.com/NativeScript/docs/pull/1243)

**Comment by CoreyCole** [comment]
@NickIliev could we also add a "Note:" to the [Router Outlet](https://docs.nativescript.org/core-concepts/angular-navigation#router-outlet) section because I missed this detail when `application-without-page-router-outlet` is at the bottom of that documentation page.

Either that or move the `application-without-page-router-outlet` section up to below `page-router-outlet`

**Comment by CoreyCole** [comment]
Opened a PR https://github.com/NativeScript/docs/pull/1317
