### ISSUE TITLE
Styling.html Page.css clarification request

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/docs-v7#130]
Based on reading the source code and some experiments, I believe the documentation at http://docs.nativescript.org/styling.html#page-specific-css is a bit faulty.   It does not appear to be clear that if you attempt to set the Page.css property you are actually eliminating all CSS except the Application wide CSS.   So if you use **Page.addCss="..."** or **Page.addCssFile(...)** and then do a **Page.css = "...";** you will wipe out any and all other css that was added via all the prior calls.

**Comment by tjvantoll** [comment]
Wow, it’s been awhile 😄 

I agree with @NathanaelA. I’m going to add the up-for-grabs label. If a community member wants to contribute this I’m happy to help. Ping me on [Slack](http://developer.telerik.com/wp-login.php?action=slack-invitation) (tjvantoll).

**Comment by NickIliev** [comment]
@NathanaelA , @tjvantoll 
Based on the [documentation article](http://docs.nativescript.org/ui/styling#page-specific-css):

> You can override CSS styles specified in the file by using the page's **css** property:

I think this line is self-explanatory and covers the described behavior, isn't it?

**Comment by sittingbool** [comment]
I agree: it's not. How do I access this property in Angular? Do I insert it as a Service? I did that and it doesn't work. Or do I call it on the class? Otherwise the this.page is missing in the documentation, which in general only explains non-angular behavior.

**Comment by tjvantoll** [comment]
@sittingbool [The Angular version of the styling page](http://docs.nativescript.org/angular/ui/styling.html#page-specific-css) doesn’t have a corresponding section on this because it works a bit differently. For most things you’ll want to [style at the component level](http://docs.nativescript.org/angular/ui/styling.html#component-specific-css) when working in Angular.

If you really need access to `this.page`, there’s a section at the beginning of [Angular getting started guide](https://github.com/NativeScript/docs/issues/130#issuecomment-317255263) that shows you how to get that reference, but essentially you just add `private page: Page` as a parameter in your component’s constructor function.

**Comment by renestalder** [comment]
I have quite the same problem. For me it's not that clear how it works in Angular. Normally, I would use the default way for CSS declaration in Angular. But the documentation for angular lists the two methods with accessing page too, which is confusing.

![screen shot 2017-11-14 at 17 44 35](https://user-images.githubusercontent.com/105358/32792514-c81b04e8-c963-11e7-8c43-f01481529679.png)

Also component based styles don't load for me, even the path is correct (which I can verify). Only app wide. So I wondered If I have to do extra steps with the page object to make this working.
