### ISSUE TITLE
Error in binding example TypeScript

### ISSUE THREAD

**Issue by lord-saumagen** [NativeScript/docs-v7#1497]
Dear Ladies and Gentlemen,

it came to my attention that the TypeScript playground example at the following URL is erroneous.

URL: https://play.nativescript.org/?template=play-tsc&id=pOnwov&v=2

![playgrounerror](https://user-images.githubusercontent.com/9468599/50960644-2a768000-14c6-11e9-8c94-53af84e2d1b0.png)

As you can see in the screen shot, there is an "ActivityIndicator" placed in the home-page.xml file after the closing page tag. The location where the "ActivityIndicator" is placed renders the xml file invalid.
There is also no "IsBusy" property define on the binding context.

Kind regards, Lord Saumagen.

**Comment by darind** [comment]
@lord-saumagen, to make this XML markup valid, the `<ActivityIndicator>` element must be nested inside the `<Page>` root element. Also, this playground example doesn't seem to use a separate view model for the `home-page` and as a result the `isBusy` property needs to be defined on the corresponding element:

```typescript
const source = fromObject({
    items: list,
    isBusy: true
});
```

Also note that without a separate view model file, the components `drag&drop` functionality of the Playground might not work properly because it might not be able to figure out the proper place to insert the binding properties.

Here's an example that you might tryout: https://play.nativescript.org/?template=play-tsc&id=9yl0bz

**Comment by darind** [comment]
@lord-saumagen, thanks for the update. We will fix the documentation link.

**Comment by tsonevn** [comment]
fixed with https://github.com/NativeScript/docs/pull/1499
