### ISSUE TITLE
Document the usage of discarded exception handler for error handling

### ISSUE THREAD

**Issue by etabakov** [NativeScript/docs-v7#1541]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[ ] Missing documentation
[X] New article needed

### Please, tell us more details
A new article is needed that explains the usage of the discardedError handler for improved error handling.

**Comment by mbektchiev** [comment]
It turns out that we already have documentation for setting a discarded exception handler:

https://docs.nativescript.org/core-concepts/ios-runtime/custom-flags#discarding-javascript-exceptions-when-called-from-native

https://docs.nativescript.org/core-concepts/android-runtime/advanced-topics/custom-flags#discarding-javascript-exceptions-when-called-from-native

https://docs.nativescript.org/api-reference/modules/_application_#discardederrorevent

https://docs.nativescript.org/api-reference/interfaces/_application_.discardederroreventdata
