### ISSUE TITLE
Merge all the Changelogs into one

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/docs-v7#161]
Lets start to have only a single Changelog for all the repos, as currently there is no a single place where to point customers to see the changelog for a particular version. 

An easy to implement idea is to just have a placeholder article that links to the existing changelogs.

**Comment by ErjanGavalji** [comment]
The thing is, while the teams output the releases together for the time being, once the things get more stable, each package (runtimes, CLI, etc) will have its own release pace.

Thus, a common article will get confusing. I guess, instead of solving a problem, we will replace it with a different problem.

The router-article however seems a perfect idea:

One article, named `Changelogs`; containing links to the various things...

And, probably, containing the changelog entries of the latest release of each package?

**Comment by tjvantoll** [comment]
@ErjanGavalji: Can we close this now that https://docs.nativescript.org/releases/changes exists? Seems like it accomplishes the goal quite well.

**Comment by ErjanGavalji** [comment]
👍 Closing it...
