### ISSUE TITLE
Get Started / CLI Basics - Creating Application

### ISSUE THREAD

**Issue by Tusshu** [NativeScript/docs-v7#1940]
### Please, tell us what's the problem?
[ ] A typo
[*] Wrong documentation
[ ] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details
Describe in more details

The following command in the documentation does not work for MacOS Big Sur v11.2, nativescript version 7.1.2 and node version 14.15.2:

tns create HelloWorld --template tns-template-blank

This generates error: 
The "path" argument must be of type string. Received null

The correct command is: 

tns create ProjectName --template @nativescript/TemplateName

This needs to be corrected.

**Comment by avats-dev** [comment]
Hi, @rigor789 can you guide me how can I resolve this and where? I would like to take up on this.

**Comment by rigor789** [comment]
@avats-dev thanks for the interest, these are here: https://github.com/NativeScript/docs/blob/master/docs//start/cli-basics.md

(Fastest way to find the correct file is to look for the "Improve This Article" on the website). This looks like it has been already fixed - just need to trigger a deployment of the site (which is a manual trigger for now - as it's quite a complex build setup).

Fixed by https://github.com/NativeScript/docs/pull/1941
