### ISSUE TITLE
Typings in Typescript plugins

### ISSUE THREAD

**Issue by the-reality-engineer** [NativeScript/docs-v7#206]
After reading through http://docs.nativescript.org/plugins/plugins and http://docs.nativescript.org/plugins/ui-plugin

It is still not entirely clear to me how a typescript plugin should be made aware of the various type declarations in the nativescript platform (including core modules and/or native types).

**Comment by tjvantoll** [comment]
This is a great suggestion that I think we should totally cover. Adding up-for-grabs. If anyone stumbles upon this and is interested in contributing feel free to send a pull request. If you need help getting started you can ping me in the [community Slack channel](http://developer.telerik.com/wp-login.php?action=slack-invitation) (I’m tjvantoll).

**Comment by radeva** [comment]
Hi @speigg ,

This topic is not related to plugins only and that's why it is described in [the core concepts](https://docs.nativescript.org/core-concepts/accessing-native-apis-with-javascript#intellisense-and-access-to-native-apis-via-typescript). Let me know if this is what you're looking for. 

If you start [building your plugin using the NativeScript Plugin Seed](https://docs.nativescript.org/plugins/building-plugins#the-nativescript-plugin-seed) this comes for you out of the box.

Best regards,
Vesi

**Comment by radeva** [comment]
Hi @speigg ,

Since there is no response in the last 2 weeks, I assume you managed to find the information needed and I'm closing this issue. 

Best regards,
Vesi
