### ISSUE TITLE
Can't connect with tj.vantoll@gmail.com account

### ISSUE THREAD

**Issue by anargu** [NativeScript/docs-v7#209]
When i was following the nativescript guide (sample groceries) I couldn't visualize the list that supposely is contained in the tj.vantoll@gmail.com account. I was checking for any errorcode in the views models.js (grocery-view-model and user-view-model...). So i want to know how can I visualize it.

Thanks in advance.

Anargu

**Comment by tjvantoll** [comment]
Hi @anargu,

Sorry you ran into problems 🙁. I’d recommend looking at the [end branch of the Groceries sample](https://github.com/NativeScript/sample-Groceries/tree/end) so that you can see the finished version of the tutorial.

Also check your terminal for any errors, as that should help you figure out what’s up.

Best of luck 😃

**Comment by tjvantoll** [comment]
Closing this issue for now. @anargu let us know if you need anything else.
