### ISSUE TITLE
Use .xml extension for view files

### ISSUE THREAD

**Issue by jmarchello** [NativeScript/docs-v7#380]
The .html extension should not be used for view files.

In Section 3.3 it states: 

> You’re free to provide any suffix for your NativeScript template file names. This guide uses .html suffixes, even though NativeScript templates aren’t HTML code, because that suffix tends to provide the best syntax highlighting in common development IDEs. This guide does not use .xml suffixes because Angular 2 syntaxes like (tap) and [text] are not valid XML.

Syntax highlighting should not be the deciding factor for a framework's conventions. The view files are XML and should thus be shown as such. If someone wants to change the highlighting, they can configure their editor/IDE accordingly. 

I'm willing to submit a PR to revise this, but I wanted to see if there were any other reasons for this decision that I am unaware of.

**Comment by tjvantoll** [comment]
Hey @jmarchello,

Because the files aren’t valid XML with Angular syntax quirks—`()`, `[]`, `[(ngModel)]`, and so forth—the NativeScript CLI’s XML validation flags these files as invalid, because they are. We actually use an HTML parser on the templates, so the `.html` suffix isn’t only about editor highlighting.

But your point is well taken. I personally don’t really like either option. The files aren’t XML but they aren’t HTML either. We thought about a new custom suffix like `.nsml`, but that feels icky too. We’re open to ideas and feedback here.

Ping @hdeshev because I know he has some thoughts here.

**Comment by jmarchello** [comment]
Ok, I was unaware that you used an html parser. That makes more since. Thanks for getting back to me.

**Comment by tjvantoll** [comment]
No worries at all. If you were thinking that I’m sure many others will as well. I noted the parser in the guide with 06c0667a43c8fad9661d57edf8e053a7d3fb7b21.

Appreciate the feedback.
