### ISSUE TITLE
Documentation: Modifying App_Resources requires new build & sometimes uninstalling app

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/docs-v7#393]
This comes up almost daily on the slack channels.

Users are working on their app, they add an image into the _App_Resources_ folder and expect it to be added to their app when they run it again and they're shocked that it is not and think things are broken.

Steps to fix: 
- Uninstall any versions of the app from the device/emulators
- Do a new build
- Run the new build (install the new app) so that it actually has the assets from App_Resources

**Comment by tjvantoll** [comment]
This indeed comes up all the time, but I’m not sure where the best place to document this though. This seems like a little too much information to include in the guide—just because I try to be selective there to avoid overloading people with new information.

My gut says a new entry on the Troubleshooting page would be best: http://docs.nativescript.org/start/troubleshooting. That way when someone brings up this problem on Slack or Stack Overflow at least we have a thing to link to instead of spelling the whole problem out.

PRs welcome 😄
