### ISSUE TITLE
Docs buttons are huge

### ISSUE THREAD

**Issue by teodorszeltins** [NativeScript/docs-v7#472]
I think this might be a bug. Buttons on doc page are gigantic. About 640x100 pixels. Click on image to see actual size.  

![image](https://cloud.githubusercontent.com/assets/1449114/17530022/64ec9c8e-5e7e-11e6-98cf-66ade4cc31bb.png)

In fact, all UI for docs if gigantic. I have a large monitor and things still don't fit in one screen.

**Comment by tjvantoll** [comment]
Hey @teodors,

Thanks a lot for the feedback. These particular buttons are only used on the home page, and were designed to be large to grab the user’s attention—but I definitely agree that the current size is excessive, perhaps extremely excessive 😄 

We have some design updates in the works, and I just passed this bit of feedback along to the appropriate people. We also have [plans to open source our docs infrastructure](https://github.com/NativeScript/docs/issues/463), so that people can contribute style changes directly.

Feel free to pass this sort of thing along anytime; we appreciate it.
