### ISSUE TITLE
Tap sensitivity

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/docs-v7#476]
Hello everyone,

I am developing a nativescript application and I am having an issue with the tap sensitivity.  Sometimes I have to tap several times before the tap gets invoked.  This happens on both, android and ios.  I have not been able to spot any pattern.  The problem occurs intermittently.

I tried increasing the size of the element that triggers the tap event, but this did not seem to have any effect.

Has anyone noticed that and if so, what can I do to eliminate this problem.

Thank you.

P.S.  The only thing I have noticed is that the problem is more pronounced in the sliding drawer, which I am using as a menu.  Sometimes I have to tap 2-3 times before the tap registers.

**Comment by tjvantoll** [comment]
Hey @dpdragnev,

This repo is for issues with the NativeScript documentation, and not for general support questions. If you post this question on Stack Overflow with the “NativeScript” tag our community will see the question and should be able to help you out. You’ll probably want to include some small code samples as well, because off the top of my head I’m not sure what’s up, as I haven’t had these issues with the `tap` event before.

**Comment by dpdragnev** [comment]
Darn it,  I am sorry,  I just noticed that I posted this on the wrong repo.  Sorry about that.  I will look for help on Stackoverflow.  

Thanks.
