### ISSUE TITLE
Question about where to find a doc for contribution

### ISSUE THREAD

**Issue by chief10** [NativeScript/docs-v7#480]
I would like to start making some edits/contributions to the documentation for Nativescript but for some of the pages, I have no clue where to find them.

For example, when I try editing the page https://docs.nativescript.org/cookbook/location, in the files, I drill down to "docs / cookbook" but only see "formatted-string-ng" and "tab-view".

Any suggestions as to where I can find that file, along with some other's I am looking for? 

Thanks!

**Comment by tjvantoll** [comment]
Hey @chief10,

Awesome that you’re looking to contribute! Confusingly, the cookbook articles are actually stored in the modules repository (see https://github.com/NativeScript/NativeScript/blob/master/tests/app/location.md, for instance), which unfortunately makes them a bit more difficult to contribute to.

The good news is we’re actively working on completely reworking that. See https://github.com/NativeScript/nativescript-sdk-examples-ng to get an idea of where we’re heading.

That does mean that the current cookbook content is not something I’d recommend changing right now—just because it’s going away very soon. If you’re interested, I can make some other suggestions for things you can contribute changes to, and there’s always the [“up-for-grabs” issues](https://github.com/NativeScript/docs/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs). We also have our [NativeScript Snacks](http://www.nativescriptsnacks.com/) site, where you can contribute small snippets of code to solve a common task.

I guess you’ll have to let me know what you’re interested in.

**Comment by chief10** [comment]
Hey @tjvantoll,

Thanks for getting back to me about this and with such a thorough response; was not expecting that. 

Ill definitely take a look around the up-for-grabs stuff and the Nativescript snacks stuff. 

I do have one last question: On the [page for creating a UI plugin](https://docs.nativescript.org/plugins/ui-plugin), it looks like the example snippets of code for the number-picker plugin are of the compiled typescript -- save the TS module declaration. Is there anyway I could see what the original typescript files for those pieces of code look like? 

Thanks a ton for all the time you guys are putting into this project and keep up the good work!

**Comment by tjvantoll** [comment]
Hey @chief10,

Just to follow up on this as I totally missed your question, that number picker is actually written in JavaScript, which I sort of agree is a bit odd. See https://github.com/atanasovg/nativescript-number-picker. I’d love to see that page changed to just have everything written in TypeScript.

Also just thought I’d note that the SDK examples documentation I mentioned earlier is now live, see for example https://docs.nativescript.org/angular/sdk-examples/action-bar.html. We’ve got some contributor documentation at https://github.com/NativeScript/nativescript-sdk-examples-ng in case you’re interested :)

I’m going to close this issue for now, but if you have any other questions feel free to reach out.
