### ISSUE TITLE
Better language separation

### ISSUE THREAD

**Issue by stephenlacy** [NativeScript/docs-v7#49]
The blocks of JavaScript and TypeScript are very similar in nature, and when next to each other do not always show the language type: https://github.com/NativeScript/docs/blob/master/ui-with-xml.md#declaring-application-mainmodule-and-start-the-application

Would you accept a PR for adding a language declaration above or in the language example block?
###### Navigate to page using Frame navigate() method

_JavaScript_

``` JavaScript
// Navigate to page called “my-page”
frames.topmost().navigate("app/my-page")
```

_TypeScript_

``` TypeScript
// Navigate to page called “my-page”
frames.topmost().navigate("app/my-page")
```

**Comment by ikoevska** [comment]
This is definitely something that we will accept a PR for.

The origin of this issue is that the documentation sources have been developed with the output at docs.nativescript.org in mind. There, the code blocks get tabs with the language clearly identified. However, we haven't taken into consideration the fact that when read in GitHub, these tabs do not appear and there is no visual distinction between the code blocks.

So, please, feel free to go ahead and submit a PR for this issue (referencing the issue as well).

**Comment by ErjanGavalji** [comment]
I'm closing the issue for @ikoevska is right that the [http://docs.nativescript.org](http://docs.nativescript.org) website should be read instead. The sources of the documentation can be used as well, but not the preferred approach due to the limitations of markdown.
