### ISSUE TITLE
NativeScript Core with TypeScript

### ISSUE THREAD

**Issue by adamvoss** [NativeScript/docs-v7#580]
The documentation pushes towards using TypeScript if using Angular 2 and using JavaScript otherwise.  There should be no reason you cannot make a Angular app with JavaScript or a NativeScript Core app with TypeScript and it would be nice for the docs to support users in that choice.

I understand that part of why it was implemented as is, is probably the effort; however, would you be interested in or open to a community contribution providing TypeScript support to the NativeScript Core tutorial?  I am thinking of the tabstrip boxes you have on the [navigation page](http://docs.nativescript.org/core-concepts/navigation) that lets the reader click the language they want.

Other than not knowing how to port `ios-swipe-delete.js` from step 6, I have already gone through the tutorial writing an implementation in TypeScript.

**Comment by NickIliev** [comment]
Hey @vossad01  in order to port ios-swipe-delete.js in TypeScript you will need [tns-platfrom-declarations](https://www.npmjs.com/package/tns-platform-declarations) as in this file you are accessing the native iOS API and for that to happen with TypeScript you will need the declaration files. 
From that point you can access the native iOS API following these rules [here](http://docs.nativescript.org/runtimes/ios/marshalling/Marshalling-Overview).
