### ISSUE TITLE
How to implement importing iOS library NativeScript plugin(TypeScript) for Angular2 + NativeScript project

### ISSUE THREAD

**Issue by wantaek** [NativeScript/docs-v7#581]
###Did you verify this is a real problem by searching [Stack Overflow]

Yes

###Tell us about the problem

I have try to find that import iOS library NativeScript plugin sample source for several days.
But I can't find sample source.
Would you mind letting me know how to implement importing iOS library NativeScript plugin?

Thanks.

###Which platform(s) does your issue occur on?

I test in iOS.

**Comment by NickIliev** [comment]
In order to access native APIs you will need to read the article about [marshalling](http://docs.nativescript.org/runtimes/ios/marshalling/Marshalling-Overview). The principle is exactly the same in both NativeScript Core and in NativeScript + Angular-2 applications with a little exception - you will have to modify a bit your tsconfig.json and references.d.ts files for Angular-2 a bit more.

[Here is the plugin](https://www.npmjs.com/package/tns-platform-declarations) that you need at the initial point.
Then you need to modify your references.d.ts [like this one ](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/references.d.ts) and your tsconfig.json  should include the lib option like [this one](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/tsconfig.json)
