### ISSUE TITLE
Discourage 2-way data binding

### ISSUE THREAD

**Issue by realtebo** [NativeScript/docs-v7#599]
I don't know if this is the right place for this issue, but I'm referring at this page: http://docs.nativescript.org/angular/tutorial/ng-chapter-3.

I suggest to completly remove the "Exercise: Two-way data binding with Angular 2 ", or add the righe and appriopritate way to do a simple event handling in this case.

Since ng2 born, 2-way data binding is discourage, please follow this guideline even you.

PS: your documentation is simply great!

**Comment by NickIliev** [comment]
Ping @tjvantoll your opinion on this ^^^ ?

**Comment by tjvantoll** [comment]
Hey @realtebo,

Sorry we missed this issue when it came in, and thanks for the feedback. Could you show where the Angular team is actively discouraging the use of two-way data binding? I’ve spent a lot of time on their documentation—here’s [the page on implementing forms](https://angular.io/docs/ts/latest/guide/forms.html), for example—and I don’t see any mentions of this concern.

Personally I’d like to leave this example in the tutorial because it’s a very common need.

**Comment by realtebo** [comment]
> Could you show where the Angular team is actively discouraging the use of two-way data binding

Is a my conclusion based on fact that is no more the default way in Angular >=2.
If I taken a mistake, feel free to ignore. It was just a suggestion.

I must admit che after more learning, I understand that my issue has not a lot of sense. 
So I close
