### ISSUE TITLE
Two CSS differences when reaching Chapter 4

### ISSUE THREAD

**Issue by ghost** [NativeScript/docs-v7#614]
In Chapter 4 of the Typescript tutorial, the following image is what the app should look like:

![image](https://cloud.githubusercontent.com/assets/5335826/20901582/263d67cc-bb01-11e6-8ce6-649f45ef5c63.png)

However, as I've followed the tutorial to this point, my application looks like this:

![desktop 12 05 2016 - 15 35 09 04](https://cloud.githubusercontent.com/assets/5335826/20901629/5b362518-bb01-11e6-95f5-888c0c198700.png)

Since I've followed the tutorial up until this point, there are two differences.  The innocuous one is the sizing and centering of the login StackLayout. I've found a simple solution to be to add `margin-top` and `margin-bottom` to the `login-common.css`.  The other is the background image, which is zoomed in on the top-right.  I'm not sure how to address that discrepancy.

The only CSS styles I have are those copied and pasted from Chapter 2.

**Comment by tjvantoll** [comment]
Hey @gbhojraj,

Sorry you ran into problems here. The height of the login box should actually happen based on this line of CSS: https://github.com/NativeScript/sample-Groceries/blob/b19537c60e84d306fa2b89199822ed654ee0a27d/app/pages/login/login.android.css#L2. Is that CSS present in your project?

I’m going to have to look into the background problem, because off the top of my head I have no idea what I did 😄  In master of Groceries I’m using some of our newly supported background properties to make this image look right. See https://github.com/NativeScript/sample-Groceries/blob/b68409f51336a4af008782703c7e417d0cdce685/app/login/login-common.css#L6-L11. I should be doing that in the tutorial, but I don’t appear to be. I’m putting this on my list of things to address the next time I make a pass through the tutorial content.

**Comment by ghost** [comment]
Thanks @tjvantoll ! It looks like, at least in the ng tutorial, there are no instructions for login.android.css in Chapter 2.

**Comment by tjvantoll** [comment]
Well that’s what I get for testing the last time through in iOS only :P Thanks for letting me know.

**Comment by ghost** [comment]
I found the difference for the background. In the tutorial, we add the background during `ngOnInit()` in `login.component.ts`.  In the sample-Groceries master file, the background is added via CSS in [`login-common.css`](https://github.com/NativeScript/sample-Groceries/blob/master/app/login/login-common.css).

Adding the line `this.page.addCss("Page {background-size: cover}");` to `ngOnInit()` fixes the issue without having to edit the CSS (to keep in line with the flow of the tutorial)
