### ISSUE TITLE
move all docs articles to this repo

### ISSUE THREAD

**Issue by kazemihabib** [NativeScript/docs-v7#618]
Hi,some of articles that are available  https://docs.nativescript.org are not in this repository.
as finding them are really hard . for example articles of containers are here https://github.com/NativeScript/NativeScript/tree/master/tests/app/ui/layouts .
it would be really good if they moved to this repository.

**Comment by NickIliev** [comment]
Hey @kazemihabib the reason why some of the articles are not in the docs repository is because they are generated after compiling real code snippets by test applications via snippet-extractors (basically talking about everything in "Code samples" for Angular and in "Cookbook" for NativeScript Core). The automation allows us to test each snippet and generate appropriate markdown article.
If we create static examples, they would be easily reachable but not tested, which is a great downside to an active product like NativeScript which is constantly evolving with new releases on every few weeks.
