### ISSUE TITLE
where could I find the useable-native-apis

### ISSUE THREAD

**Issue by 1392324000** [NativeScript/docs-v7#624]
In article <**accessing-native-apis-with-javascript**> ,it tells us how use naive-Apis with js code,it's good.

But,I don't know where is the native-Apis because I never come into Android .Is it a neccesary baisc to know about Android knowledges for all Nativescript learner?

So I turned to Android developer site to find the list ,and I falled in an other rabbit hole,--it's so complicate to me.

Can you give us a **usable-native-Apis-list** to access the native-Apis easily?

**Comment by NickIliev** [comment]
@1392324000 the Android API is enormously big and can be indeed intimidating for a newcomer.
The better approach is to look for what you need and search specifically for it (even Android devs does not bother to learn or read the whole API reference)

For example, let's assume that I need access to the Downloads directory on Android phone though the file system in order to save a file. After a quick research, I am aware that the method needed is called getExternalStoragePublicDirectory but I am not so sure how to use it so the next thing is to open the native Android API and look for references.

Here is the direct link in the Android API refernce: [https://developer.android.com/reference/android/os/Environment.html#getExternalStoragePublicDirectory(java.lang.String)](https://developer.android.com/reference/android/os/Environment.html#getExternalStoragePublicDirectory(java.lang.String))

Now knowing that this method comes from [Environment class](https://developer.android.com/reference/android/os/Environment.html) here is how to get the path for it in NativeScript

```
var androidDownloadsPath = android.os.Environment.getExternalStoragePublicDirectory(
            android.os.Environment.DIRECTORY_DOWNLOADS).toString();
```
