### ISSUE TITLE
layout-containers doc for "Sample (fixed and auto)" has code different than description specifies

### ISSUE THREAD

**Issue by Hakier** [NativeScript/docs-v7#655]
In description You can read: "The second column and the second row have fixed sizes of 30 and 50 respectively", but the code ```<GridLayout columns="100,auto" rows="100,auto"></GridLayout>``` implies that second column will have as much place as widest child element requires.

I think that should be ```<GridLayout columns="100,30" rows="100,50"></GridLayout>```.

In "Sample (Create grid dynamically via code behind)" there is lack of info how to use this as template. I have tryed ```@Component({
    selector: "my-app",
    template: GridLayout.toString(),
})``` but it not works

**Comment by tsonevn** [comment]
Hi @Hakier,
Thank you for reporting the issue with example description for the `GridLayout`. 
This has been fixed with PR:[#667](https://github.com/NativeScript/docs/pull/667)

About your second question [here](https://docs.nativescript.org/cookbook/ui/layouts/grid-layout) you will find description, how to create `GridLayout` from code behind
