### ISSUE TITLE
What's the purpose of bundle-config.ts

### ISSUE THREAD

**Issue by mn-martin** [NativeScript/docs-v7#674]
I've created my project using `tns create Example --tsc` using tns@2.5.0 and found a file in my app directory which i don't know the purpose of: [View the file on GitHub (bundle-config.ts)](https://github.com/NativeScript/template-hello-world-ts/blob/master/bundle-config.ts)

It registers a main-page module globally I guess, but:
* main-page is a Component not a Module (isn't it?)
* if I remove that registerModule call entirely nothing happens
* if I try registering my own components it doesn't seem to work (I still need to add xmlns to my Page and removing the registerModule call here makes no difference either)

I think this file should be removed from the template altogether or the documentation needs an update. (I think it's just some unused sample file for people that want to explore Webpack bundling - is it?)

**Comment by NickIliev** [comment]
Hey @mn-martin 

The [bundle.js](http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html#inspecting-bundles) file is used for bundling your application with webpack. Creating a webpack bundle will reduce your application size and will also improve performance. To ease the process of implementing webpack we have introduced the base files needed for bundling in our templates so this is the reason for you to see `bundle.js`. Removing this file will be critical only if you use webpack. Otherwise, it does not make any difference for your application.

More about bundling can be found [in this documentation article](http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html#using-webpack-to-bundle-your-code)
