### ISSUE TITLE
"Get Started" Buttons switch places

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#675]
_From @philippsander on February 7, 2017 15:46_

http://docs.nativescript.org/angular/start/introduction.html

The 2 buttons switch places randomly when reloading the page

_Copied from original issue: NativeScript/NativeScript#3601_

**Comment by tjvantoll** [comment]
Hey @NickIliev,

This is actually purposely done with a bit of JavaScript in https://github.com/NativeScript/docs/blob/production/start/introduction.md.

We do this because we’re interested in tracking user preference between the two tutorials, and we don’t want the results skewed by which button appears first.

This is potentially confusing to users that refresh the page, but Dan and I would like to leave this randomization in place, at least for the time being. If enough people complain about this behavior we can certainly reconsider.

**Comment by philippsander** [comment]
@tjvantoll haha wow.

you should track what's already chosen and make the button reappear on the same spot ;-)

**Comment by tjvantoll** [comment]
@philippsander Ah, good suggestion! I’ll reopen this so we can implement that. A bit of `sessionStorage` logic should do the trick.

**Comment by etabakov** [comment]
Closing the issue as there are no longer two buttons and the Get Started buttons in the respective section (Core or Angular) will bring you to the right place.
