### ISSUE TITLE
Linux install instructions are outdated

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/docs-v7#678]
Hi, with the release of NS 2.5, Android SDK Build-tools has to be 25.0.2 or later, but the instructions are still installing 23. It might be an issue on other instruction pages as well, but I found this specifically on the Linux one https://docs.nativescript.org/start/ns-setup-linux

sudo $ANDROID_HOME/tools/android update sdk --filter tools,platform-tools,android-23,build-tools-23.0.3,extra-android-m2repository,extra-google-m2repository,extra-android-support --all --no-ui

**Comment by tsonevn** [comment]
updated with PR https://github.com/NativeScript/docs/pull/702

**Comment by agrcrobles** [comment]
Hi there,

I just found that the following instructions are not good on linux when installing the NativeScript CLI.

```
sudo npm install nativescript -g --unsafe-perm
```

Instead it should be done without `sudo` 

That is because npm should run always without `sudo` on any linux even using yarn or nvm.

https://github.com/NativeScript/docs/blob/master/docs/start/ns-setup-linux.md

Thanks,
