### ISSUE TITLE
Android requirements are not good defined.

### ISSUE THREAD

**Issue by OscarArnaizLopez** [NativeScript/docs-v7#815]
Current docs for supported API levels in Android  say:

_"The Android Runtime is built against API level 17. The minimum supported compile SDK version is 22."_ 
This should be the opposite:
_"The Android Runtime is built against API level 22. The minimum supported compile SDK version is 17"_

**Comment by petekanev** [comment]
Hey @OscarLopezArnaiz,

The android runtime is in fact built using compileSdk 23, with support in mind of devices as low as API Level 10.

The core-modules however, that the technology depends on, and is the core of all that is NativeScript, can be ran on devices as low as API Level 17.

Now, when building applications, you can explicitly specify the compileSdk version you want to build your app against, and that needs to be 22+ at the time of writing, because there are certain components that can't compile if built against a lower compileSdk level, hence the original text.
