### ISSUE TITLE
Hello world from CLI lacks emulator image setup mention

### ISSUE THREAD

**Issue by Dunemaster** [NativeScript/docs-v7#91]
http://docs.nativescript.org/hello-world/hello-world-ns-cli.html

Scetion "3. You can quickly check how your blank project looks like in the emulator or on device." suggests running created app on emulator right away, without mentioning that setting up an image is required.

**Comment by ikoevska** [comment]
The section clearly states "For example, the following runs your app in the iOS Simulator or an Android AVD **configured on your machine**."

However, we could explicitly state in the setup documentation that users should set up their emulator devices on their own.

**Comment by tjvantoll** [comment]
The new getting started guide does give a warning for this now. See “setting up an AVD” [here](https://github.com/NativeScript/docs/blob/master/getting-started/chapter-1.md#----exercise-run-your-app), which I think helps. I'm wondering if there's a better place we could link to though. Not because [this](http://developer.telerik.com/featured/using-android-emulator-hybrid-mobile-apps-telerik-appbuilder/#managing-avds) is a bad article, but because it takes the reader somewhat out of context.

**Comment by tjvantoll** [comment]
Closing in favor of https://github.com/NativeScript/docs/issues/358.
