### ISSUE TITLE
Console.log examples is not working on MacOS Sierra 10.12.6

### ISSUE THREAD

**Issue by ricemann** [NativeScript/docs-v7#917]
If I need to make a pull-request I will - but maybe someone could make a note that in order to actually show log messages - you have to debug instead run. Let me explain:

$> tns debug ios; 
or 
$> tns debug android;

Will show log messages.

$> tns run ios; will not.

Took me some time to figure out - both tutorials are great but not clear about this matter : )

Btw - NativeScripts is Awesome - thank you all.

Riceman

**Comment by tsonevn** [comment]
Hi @ricemann,
Thank you for pointing this issue and indeed there is an issue with the `console.log`, while using ios 11. 
However, this is already reported [here ](https://github.com/NativeScript/NativeScript/issues/4867) and I would suggest keeping the discussion on the other one.
Something more every pull request, which fixes this issue will be highly appreciated. For further help you could also review our contribution guidelines [here](https://www.nativescript.org/contribute).
In case you think that this issue is different, I will reopen the it
